INSERT into blogger(username, email, password, name, created_at) VALUES('savvyblogger', 'savvyblogger@example.com', 'myblogpass1', 'Sarah Johnson', CURRENT_TIMESTAMP), ('travelholic', 'travelholic@emailprovider.com', 'globetrotter22', 'Jason Anderson', CURRENT_TIMESTAMP), ('fashionista89', 'fashionlover89@example.com', 'stylequeen123', 'Emily Davis', CURRENT_TIMESTAMP), ('techgeek21', 'techgeek21@domain.com', 'coding1234', 'Alex Turner', CURRENT_TIMESTAMP), ('foodiegram', 'foodiegram@domain.com', 'delicious1', 'Mia Thompson', CURRENT_TIMESTAMP);
INSERT into post(blogger_id, title, content, created_at) VALUES(6, "5 Essential Tips for Successful Blogging", "Hey fellow bloggers! Today, I want to share some valuable tips that have helped me succeed in the blogging world. Firstly, find your niche and focus on topics you're passionate about. Authenticity is key! Secondly, consistency matters. Set a regular posting schedule and stick to it. Thirdly, engage with your readers by responding to comments and encouraging discussions. Building a community is vital. Fourthly, promote your blog on social media platforms to expand your reach. Lastly, remember to enjoy the journey! Blogging is a creative outlet, so have fun and be yourself. Happy blogging!", CURRENT_TIMESTAMP);
INSERT into post(blogger_id, title, content, created_at) VALUES(7, "Unforgettable Travel Experiences: Exploring the Wonders of Japan", "Konnichiwa, travel enthusiasts! Join me on a virtual journey to Japan, a land of ancient traditions and modern marvels. From the bustling streets of Tokyo to the serene temples of Kyoto, Japan offers an array of unforgettable experiences. Discover the vibrant cherry blossom season, soak in the natural hot springs of Hakone, and immerse yourself in the rich history of Hiroshima. Don't miss the awe-inspiring Mount Fuji or the culinary delights of Osaka's street food. Japan is a country that will captivate your senses and leave you with memories that will last a lifetime. Arigatou gozaimasu!", CURRENT_TIMESTAMP);
INSERT into post(blogger_id, title, content, created_at) VALUES(8, "Fashion Trends: Embrace Your Unique Style", "Hello, fashionistas! Let's talk about embracing your unique style and staying on top of the latest trends. Remember, fashion is all about self-expression. Experiment with colors, patterns, and accessories that resonate with your personality. Mix high-end and affordable pieces to create a personalized look. Keep an eye on fashion weeks and magazines for inspiration, but don't be afraid to add your own twist. Confidence is the ultimate accessory! Don't follow trends blindly; choose what makes you feel fabulous. Fashion is a form of art, so let your creativity shine and be the trendsetter you were born to be.", CURRENT_TIMESTAMP);
INSERT into post(blogger_id, title, content, created_at) VALUES(9, "Tech Talk: Exploring the Exciting World of Virtual Reality", "Welcome, tech enthusiasts! Today, let's dive into the exciting world of virtual reality (VR). VR technology has come a long way, revolutionizing gaming, entertainment, and even education. Imagine exploring new worlds, interacting with lifelike characters, and immersing yourself in breathtaking experiences, all from the comfort of your home. From gaming headsets to VR arcades, the possibilities are endless. Whether you're an avid gamer or simply curious about cutting-edge technology, VR is worth exploring. Get ready to step into a new dimension and witness the future of digital entertainment!", CURRENT_TIMESTAMP);
INSERT into post(blogger_id, title, content, created_at) VALUES(10, "The Art of Food: Exploring Culinary Delights Around the World", "Bon appétit, foodies! Today, let's embark on a delectable journey exploring culinary delights from around the world. Discover the exotic spices of Indian cuisine, the tantalizing street food of Thailand, and the mouthwatering pastries of France. From sushi in Japan to tacos in Mexico, each culture boasts its own unique flavors and cooking techniques. Expand your palate and try new dishes whenever you can. Whether you're a home cook or a restaurant aficionado, the world of food offers endless possibilities for delicious adventures. So grab your fork and let's savor the flavors of the world together!", CURRENT_TIMESTAMP);
INSERT into comment(post_id, blogger_id, content, created_at) VALUES(2, 8, "Great tips, Sarah! Finding your niche and staying true to yourself is so important. I love how you emphasize building a community and engaging with readers. It's what sets blogging apart from other platforms. Keep up the fantastic work!", CURRENT_TIMESTAMP);
INSERT into comment(post_id, blogger_id, content, created_at) VALUES(3, 9, "Wow, Jason! Your post on Japan has me dreaming of my next travel adventure. The descriptions are vivid, and your passion for the country shines through. I'm adding Japan to my bucket list right away. Thanks for the inspiration!", CURRENT_TIMESTAMP);
INSERT into comment(post_id, blogger_id, content, created_at) VALUES(4, 10, "Emily, you nailed it! Fashion is all about expressing your unique style. I appreciate how you encourage us to be confident and embrace our creativity. Your posts always inspire me to experiment with my outfits. Keep the fabulous fashion advice coming", CURRENT_TIMESTAMP);
INSERT into comment(post_id, blogger_id, content, created_at) VALUES(5, 6, "Alex, your take on virtual reality is fascinating! It's incredible to see how far VR has come and its potential in various fields. Your post has piqued my curiosity, and I can't wait to dive into the virtual world. Thanks for sharing your insights!", CURRENT_TIMESTAMP);
INSERT into comment(post_id, blogger_id, content, created_at) VALUES(6, 7, "Mia, your post on exploring culinary delights around the world is making my taste buds dance! Your descriptions have me craving dishes from different cultures. I'm ready to embark on a gastronomic adventure and try new flavors. Thanks for the mouthwatering inspiration!", CURRENT_TIMESTAMP);
INSERT into comment(post_id, blogger_id, content, created_at) VALUES(4, 7, "Hello World! delete me", CURRENT_TIMESTAMP);

SELECT * from blogger where created_at > '2020-01-01 00:00:00.00';
UPDATE blogger set password='bad_password' where password='pass';
SELECT post.content, post.title, blogger.username FROM post INNER JOIN blogger ON post.blogger_id = blogger.id;
SELECT comment.content, post.title, blogger.username from comment INNER JOIN post ON comment.post_id = post.id INNER JOIN blogger ON comment.blogger_id = blogger.id;
DELETE FROM comment WHERE content LIKE '%delete me%';
SELECT post.id, post.content, post.title, blogger.username FROM post INNER JOIN blogger ON post.blogger_id = blogger.id WHERE post.id = (select post_id from comment GROUP BY post_id HAVING COUNT(*) >= 3);
